@startuml DS4_ObtenerCuentaCorriente
title DS4 - Obtener Cuenta Corriente del Proveedor

actor Operador
participant "ReportesController" as Ctrl
participant "Proveedor" as Proveedor

Operador -> Ctrl : consultarCuentaCorriente(cuitProveedor)
activate Ctrl
    note right of Ctrl
        Ctrl = ReportesController.getInstance()
    end note

    loop [buscar en coleccion de proveedores]
        Ctrl -> Ctrl : buscarProveedorPorId(cuitProveedor)
        activate Ctrl
            Ctrl --> Ctrl : unProveedor
        deactivate Ctrl
    end

    Ctrl -> Proveedor : obtenerCuentaCorriente()
    activate Proveedor
        note right of Proveedor
            Suma afectarCuentaCorriente()
            de cada comprobante del proveedor
        end note
        Proveedor --> Ctrl : deudaVigente : double
    deactivate Proveedor

    Ctrl -> Proveedor : getComprobantes()
    activate Proveedor
        Proveedor --> Ctrl : comprobantes : List<Comprobante>
    deactivate Proveedor

    Ctrl --> Operador : comprobantes : List<Comprobante>
deactivate Ctrl

@enduml
